version: '3.9'
services:
  builder:
    image: amazoncorretto:17-alpine-jdk
    volumes:
      - .:/opt/build
      - type: volume
        source: app_home
        target: /opt/app
        volume:
          nocopy: true
      - type: volume
        source: gradle_home
        target: /opt/.gradle:rw
    working_dir: /opt/build
    command: "/opt/build/gradlew copyDeps --gradle-user-home=/opt/.gradle -x test"
  cleanBuilder:
    image: amazoncorretto:17-alpine-jdk
    volumes:
      - .:/opt/build
      - type: volume
        source: app_home
        target: /opt/app
        volume:
          nocopy: true
      - type: volume
        source: gradle_home
        target: /opt/.gradle:rw
    working_dir: /opt/build
    command: "/opt/build/gradlew cleanDeps copyDeps --gradle-user-home=/opt/.gradle -x test"
  redis:
    image: redis
    ports:
      - "16379:6379"
  learning-app:
    build:
      dockerfile: Dockerfile
    volumes:
      - app_home:/opt/app
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      redis:
        condition: service_started
volumes:
  gradle_home:
  app_home: